{exec} = require "child_process"
fs = require "fs"


# Clean the environment
task "clean", "Clean the environment.", ->
	exec "rm -rf dist/", (err, stdout, stderr) ->
		throw err if err
		console.log stdout + stderr
		console.log "dist/ folder was deleted."


# Build the stack
task "build", "Build the stack from source files", ->
	# Compile it
	exec "rm -rf dist/; mkdir -p dist/lib; coffee -c -o dist/ script.coffee; jade -P -O dist/ index.jade", (err, stdout, stderr) ->
		throw err if err
		console.log stdout + stderr
	# Copy needed libraries to dist/ folder
	exec "cp -R lib/ dist/; cp ../../dist/qoffeesip.js dist/lib/", (err, stdout, stderr) ->
		throw err if err
		console.log stdout + stderr
		console.log "All sources were compiled to dist/ folder."
